import localFont from 'next/font/local';
import './globals.scss';
import Header from './components/Header';
import Footer from './components/Footer';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{ maxWidth: '1024px', margin: '8px auto' }}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
